config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root to: "homes#top"

  devise_for :admin, skip: [:password], controllers: {
    registrations: "admin/registrations",
    sessions: 'admin/sessions'
  }
  devise_for :master_accounts, controllers: {
    registrations: "master_accounts/registrations",
    sessions: 'master_accounts/sessions'
  }

  resources :contacts, only: [:create]
  resources :informations, only: [:index, :show]
  resources :students, only: [:index, :show] do
    resources :sakura_prints, only: [:show]
    resources :kentes, only: [:show]
    resources :rooms, only: [:index, :show]
  end



  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :rooms, only: [:index, :show]
    resources :informations, only: [:index, :create, :new, :show, :destroy]
    resources :contacts, only: [:index, :show]
    resources :students
    resources :sakura_prints
    resources :kentes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :master_accounts, only: [:index, :show] do
      resources :students, except: [:index, :show], only: [:new, :create]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]

  has_many :rooms, dependent: :destroy
  has_many :messages, through: :rooms
  has_many :sent_messages, as: :sender, class_name: 'Message', dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
  has_one_attached :image
  
  validates :title, presence: true
  validates :content, presence: true
end

app/models/kente.rb
class Kente < ApplicationRecord
  before_save :set_total_score

  belongs_to :student
  belongs_to :kente_rank
  belongs_to :kente_number

  private

  def set_total_score
    self.total_score = multiplication_score + division_score + mitori_score
  end
end

app/models/kente_number.rb
class KenteNumber < ApplicationRecord
  has_many :kentes, dependent: :destroy
  has_many :students, through: :kentes
end

app/models/kente_rank.rb
class KenteRank < ApplicationRecord
  has_many :kentes, dependent: :restrict_with_exception
end

app/models/master_account.rb
class MasterAccount < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :students, dependent: :destroy
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :sender, polymorphic: true
  
  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :admin
  belongs_to :student

  has_many :messages, dependent: :destroy
end

app/models/sakura_print.rb
class SakuraPrint < ApplicationRecord
  before_save :set_total_score

  belongs_to :student
  belongs_to :sakura_print_number

  private

  def set_total_score
    self.total_score = multiplication_score + division_score + mitori_score + mitori_anzan_score
  end
end

app/models/sakura_print_number.rb
class SakuraPrintNumber < ApplicationRecord
  has_many :sakura_print, dependent: :destroy
  validates :number, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :master_account
  has_many :sakura_prints, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :messages, through: :rooms, dependent: :destroy
  has_many :sent_messages, as: :sender, class_name: 'Message', dependent: :destroy
  has_many :kentes, dependent: :destroy
  has_many :kente_numbers, through: :kentes

  belongs_to :kente_rank, foreign_key: :rank_id, optional: true
  belongs_to :next_kente_rank, class_name: 'KenteRank', foreign_key: :next_kente_rank_id, optional: true
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  def index
    
    @students =Student.all
  end

  def show
    @student = Student.find(params[:id])
    @sakura_prints_high_score = @student.sakura_prints.order(total_score: :desc).first
    @current_rank = @student.kente_rank
    @next_rank = @student.next_kente_rank
  end

  def new
    @master_account = MasterAccount.find(params[:master_account_id])
    @student = @master_account.students.build
    @kente_ranks = KenteRank.all
  end

  def create
    @master_account = MasterAccount.find(params[:master_account_id])
    @student = @master_account.students.build(student_params)
    if @student.save
      redirect_to admin_master_account_path(@master_account), notice: "生徒を作成しました"
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
    @kente_ranks = KenteRank.all
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to admin_student_path(@student), notice: "生徒情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @master_account = @student.master_account
    @student.destroy
    redirect_to admin_master_account_path(@master_account), notice: "生徒を削除しました"
  end
  
  private
  
  def student_params
    if action_name == 'edit' || action_name == 'update'
      params.require(:student).permit(:first_name, :last_name, :last_name_kana, :first_name_kana, :rank_id, :is_active, :next_kente_rank_id)
    else
      params.require(:student).permit(:first_name, :last_name, :last_name_kana, :first_name_kana, :rank_id, :is_active)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @contact = Contact.new
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_master_account!

  def index
    @student = Student.find(params[:student_id])    
    @admins = Admin.select(:id, :last_name, :first_name)
  end
  def show
    @current_account = current_master_account
    @admin = Admin.select(:id, :first_name, :last_name).find(params[:id])
    @student = Student.find(params[:student_id])
  
    @room = Room.find_by(admin: @admin, student: @student)
  
    unless @room
      @room = Room.create!(admin: @admin, student: @student)
    end
  
    @messages = @room.messages.includes(:sender)
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_master_account!

  def index    
    @students =current_master_account.students
  end

  def show
    @student = Student.find(params[:id])
    @sakura_prints_high_score = @student.sakura_prints.order(total_score: :desc).first
    @current_rank = @student.kente_rank
    @next_rank = @student.next_kente_rank
  end
end

app/helpers/admin/students_helper.rb
module Admin::StudentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/kentes_helper.rb
module KentesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/index.html.erb
<div class="container my-4">
  <h1 class="mb-4">塾生一覧</h1>
  <div class="list-group">
    <% @students.each do |student| %>
      <div class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to student_path(student), class: "flex-grow-1 text-decoration-none text-reset" do %>
          <%= student.last_name %> <%= student.first_name %>
        <% end %>
        <%= link_to "メッセージ", student_rooms_path(student), class: "btn btn-sm btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<div class="container my-4">
  <h1 class="mb-4">塾生情報</h1>

  <div class="card shadow-sm">
    <div class="card-body">
      <dl class="row">
        <dt class="col-sm-3">氏名</dt>
        <dd class="col-sm-9"><%= @student.last_name %> <%= @student.first_name %></dd>

        <dt class="col-sm-3">フリガナ</dt>
        <dd class="col-sm-9"><%= @student.last_name_kana %> <%= @student.first_name_kana %></dd>

        <dt class="col-sm-3">さくらプリント最高点</dt>
        <dd class="col-sm-9"><%= @sakura_prints_high_score&.total_score || "0" %></dd>

        <dt class="col-sm-3">取得級位</dt>
        <dd class="col-sm-9"><%= @current_rank&.rank.presence || "未設定" %></dd>

        <dt class="col-sm-3">次回受験級</dt>
        <dd class="col-sm-9"><%= @next_rank&.rank.presence || "未設定" %></dd>

        <dt class="col-sm-3">登録日時</dt>
        <dd class="col-sm-9"><%= @student.created_at.strftime("%Y年%m月%d日 %H:%M") %></dd>

        <dt class="col-sm-3">最終更新日時</dt>
        <dd class="col-sm-9"><%= @student.updated_at.strftime("%Y年%m月%d日 %H:%M") %></dd>
      </dl>
    </div>
  </div>

  <div class="mt-3 d-flex">
    <%= link_to "一覧に戻る", students_path, class: "btn btn-secondary mr-2" %>
    <%= link_to "メッセージ", student_rooms_path(@student), class: "btn btn-primary mr-2" %>
    <%= link_to "さくらプリント成績", student_sakura_print_path(@student), class: "btn btn-secondary mr-2" %>
    <%= link_to "検定試験成績", student_kente_path(@student), class: "btn btn-secondary mr-2" %>
  </div>
</div>