config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root to: "homes#top"

  devise_for :admin, skip: [:password], controllers: {
    registrations: "admin/registrations",
    sessions: 'admin/sessions'
  }
  devise_for :master_accounts, controllers: {
    registrations: "master_accounts/registrations",
    sessions: 'master_accounts/sessions'
  }

  resources :contacts, only: [:create]
  resources :informations, only: [:index, :show]
  resources :students, only: [:index, :show] do
    resources :sakura_prints, only: [:show]
    resources :kentes, only: [:show]
    resources :rooms, only: [:index, :show]
  end



  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :rooms, only: [:index, :show]
    resources :informations, only: [:index, :create, :new, :show, :destroy]
    resources :contacts, only: [:index, :show]
    resources :students
    resources :sakura_prints
    resources :kentes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :master_accounts, only: [:index, :show] do
      resources :students, except: [:index, :show], only: [:new, :create]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]

  has_many :rooms, dependent: :destroy
  has_many :messages, through: :rooms
  has_many :sent_messages, as: :sender, class_name: 'Message', dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
  has_one_attached :image
  
  validates :title, presence: true
  validates :content, presence: true
end

app/models/kente.rb
class Kente < ApplicationRecord
  before_save :set_total_score

  belongs_to :student
  belongs_to :kente_rank
  belongs_to :kente_number

  private

  def set_total_score
    self.total_score = multiplication_score + division_score + mitori_score
  end
end

app/models/kente_number.rb
class KenteNumber < ApplicationRecord
  has_many :kentes, dependent: :destroy
  has_many :students, through: :kentes
end

app/models/kente_rank.rb
class KenteRank < ApplicationRecord
  has_many :kentes, dependent: :restrict_with_exception
end

app/models/master_account.rb
class MasterAccount < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :students, dependent: :destroy
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :sender, polymorphic: true
  
  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :admin
  belongs_to :student

  has_many :messages, dependent: :destroy
end

app/models/sakura_print.rb
class SakuraPrint < ApplicationRecord
  before_save :set_total_score

  belongs_to :student
  belongs_to :sakura_print_number

  private

  def set_total_score
    self.total_score = multiplication_score + division_score + mitori_score + mitori_anzan_score
  end
end

app/models/sakura_print_number.rb
class SakuraPrintNumber < ApplicationRecord
  has_many :sakura_print, dependent: :destroy
  validates :number, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :master_account
  has_many :sakura_prints, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :messages, through: :rooms, dependent: :destroy
  has_many :sent_messages, as: :sender, class_name: 'Message', dependent: :destroy
  has_many :kentes, dependent: :destroy
  has_many :kente_numbers, through: :kentes

  belongs_to :kente_rank, foreign_key: :rank_id, optional: true
  belongs_to :next_kente_rank, class_name: 'KenteRank', foreign_key: :next_kente_rank_id, optional: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/kentes_helper.rb
module KentesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/shared/_admin_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <div class="container">
    <%= link_to "さくらそろばん教室(管理者)", admin_dashboards_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">     
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_informations_path, class: 'nav-link text-light' do %>
              <span>お知らせ</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_dashboards_path, class: 'nav-link text-light' do %>
              <span>成績入力</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_students_path, class: 'nav-link text-light' do %>
              <span>塾生一覧</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_master_accounts_path, class: 'nav-link text-light' do %>
              <span>マスターアカウント一覧</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_contacts_path, class: 'nav-link text-light' do %>
              <span>問い合わせ確認</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_rooms_path, class: 'nav-link text-light' do %>
              <span>メッセージ</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              <span>ログアウト</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <div class="container">
    <%= link_to "さくらそろばん教室", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">     
        <% if master_account_signed_in? %>
          <li class="nav-item">
            <%= link_to informations_path, class: 'nav-link text-light' do %>
              <span>お知らせ</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to students_path, class: 'nav-link text-light' do %>
              <span>塾生情報・成績閲覧・メッセージ</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_master_account_session_path, method: :delete, class: 'nav-link text-light' do %>
              <span>ログアウト</span>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_master_account_session_path, class: 'nav-link text-light' do %>
              <span>ログイン</span>
            <% end %>
          </li>
        <% end%>
      </ul>
    </div>
  </div>
</nav>